### ISSUE TITLE
Some valid URLs marked as 'broken'

### ISSUE THREAD

**Issue by saneef** [bradleyburgess/eleventy-plugin-broken-links#2]
Hey, foremost, thanks for making this plugin!

On my blog, I have many links to github.com. When using the plugin, many of them are shown as 'broken'.

I drilled down a bit, and it looks like GitHub returns HTTP `429 Too Many Requests` if requesting a short span of time. This may a problem for other sites too.

Probably caching already checked URLs might be a good idea. Furthermore, it will make the plugin faster.

**Comment by bradleyburgess** [comment]
That's a great point, thanks for raising it.

I have an idea to move to using something like `eleventy-fetch` (which is a dependency of `eleventy-img`, so would be convenient), but I need to
investigate whether this would be possible.

**Comment by bradleyburgess** [comment]
@saneef, I just published `v1.1.0` which implements the cache using `eleventy-fetch`. It seems to be working for me. Take a look and see if it works for you. (This seemed more pressing than the verbose console [#1](https://github.com/bradleyburgess/eleventy-plugin-broken-links/issues/1), so I looked at it first.)

**Comment by saneef** [comment]
I tried `v1.1.0`. I'm still getting errors to some links to GitHub. Look to me the number of errors have reduced from before.

Two things:

**1.** Same URLs which was okay before gets error later. A URL in the footer of all pages. 

<img width="918" alt="Screenshot 2022-04-22 at 12 27 00" src="https://user-images.githubusercontent.com/81863/164622238-590704c5-33e3-4c3f-a500-7fbbd668f098.png">

Not sure why this is happening if cached.

**2.**  I didn't think of a scenario this before. The HTTP error code `429` may be caused by the requests to same domain but different paths. Through `grep` I found there are around 80+ links to (around 12 unique) GitHub. Here there are around 12 unique URLs, should cause much issue if the cache works well. Does Eleventy compile some pages parallely, causing the skip cache lookup in some way?

**Comment by saneef** [comment]
Adding to the point 2 earlier. Like you suggested in #1, probably letting the user ignore some URLs of certain domains (or through regex) likely will help. For me, links to linkedin.com returns HTTP code `999`. [Looks like same for others](https://stackoverflow.com/questions/46214017/public-linkedin-profile-url-returns-server-status-code-999).

**Comment by bradleyburgess** [comment]
I think I know what's going on. The current process is as follows:

1. "Lint" each page and gather links
2. After each page has been linted, check all links _in parallel_.

I was trying to be clever and use `Promise.all` so that I could run the HTTP requests parallel instead of `await`ing each one separately, thereby speeding things up. But now I see that's causing some grief, because I didn't eliminate non-unique URLs first. This explains why you get `okay` status and later `error` status for the same link later. 

I did this in a hurry, and I can see some pitfalls that I've walked right into. I am going to refactor a bit today and move to using a lookup so that each unique URL is only tested once. This should solve your issue and also make it faster.

**Comment by bradleyburgess** [comment]
@saneef I've done a bit of work today in getting this fixed. Check out `v1.2.0`. I think it should be a lot better; let me know.

**Comment by saneef** [comment]
Thanks @bradleyburgess for the rework!

But, I'm afraid when I use `v1.2.0` I'm faced with this error:

```sh
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] Cannot read properties of undefined (reading 'toString') (via TypeError)
[11ty]
[11ty] Original error stack trace: TypeError: Cannot read properties of undefined (reading 'toString')
[11ty]     at ExternalLink.setHttpStatusCode (/Users/saneef/workspace/saneef/saneef.com/node_modules/eleventy-plugin-broken-links/lib/ExternalLink.js:26:32)
[11ty]     at /Users/saneef/workspace/saneef/saneef.com/node_modules/eleventy-plugin-broken-links/lib/checkLinkStatuses.js:10:23
[11ty]     at Array.forEach (<anonymous>)
[11ty]     at checkLinkStatuses (/Users/saneef/workspace/saneef/saneef.com/node_modules/eleventy-plugin-broken-links/lib/checkLinkStatuses.js:7:11)
[11ty]     at async AsyncEventEmitter.<anonymous> (/Users/saneef/workspace/saneef/saneef.com/node_modules/eleventy-plugin-broken-links/.eleventy.js:24:5)
[11ty]     at async Promise.all (index 0)
[11ty]     at async Eleventy.executeBuild (/Users/saneef/workspace/saneef/saneef.com/node_modules/@11ty/eleventy/src/Eleventy.js:1012:7)
```

After I patched [the line](https://github.com/bradleyburgess/eleventy-plugin-broken-links/blob/9131510ff53c8989271377ce0d3d5370ab6fa227/lib/ExternalLink.js#L26) to `this.httpStatusCode = (code || "").toString();`, it runs fine. I couldn't figure out when `getLinkStatusCode()` returns with `httpStatusCode` not set.

**Comment by saneef** [comment]
Does it makes sense to show the HTTP code when an URL is marked broken? It might be useful once you add #4 in the future :)

**Comment by bradleyburgess** [comment]
Ok thanks, I will make that change RE `httpStatusCode` not being set. 

And yes, it definitely makes sense to show the status code. 

I'm currently working on the logging level, and will be done soon. 

But at some point I'm also going to add debugging, so that we can use `debug` and eleventy debug mode. 

I really appreciate your feedback!

**Comment by bradleyburgess** [comment]
@saneef I just patched that strange error you found, and I also added showing the HTTP Status Code to the console output if it's a broken or redirected link.

I also added a new `loggingLevel` option (see [#1](https://github.com/bradleyburgess/eleventy-plugin-broken-links/issues/1)). Available in `v1.3.0`, which I just pushed.

**Comment by bradleyburgess** [comment]
If you're happy with this, you can close the issue!

**Comment by saneef** [comment]
Yeah, thanks a lot! Works! Closing this issue.

A minor thing, this is the log from building within this repo. You see the HTTP code with `301`. It doesn't print the URL related to that request.
```
$ eleventy
[11ty] Writing _site/README/index.html from ./README.md (liquid)
[11ty] Writing _site/index.html from ./index.md (liquid)
[plugin-broken-links] HTTP Status Code: 301
[plugin-broken-links] Used 1 time(s) on these pages:
[plugin-broken-links]   - ./index.md
[plugin-broken-links] Link is broken: https://example.com/brokenlinks
[plugin-broken-links] HTTP Status Code: 404
[plugin-broken-links] Used 1 time(s) on these pages:
[plugin-broken-links]   - ./index.md
[11ty] Wrote 2 files in 0.12 seconds (v1.0.1)
✨  Done in 0.57s.
```

**Comment by bradleyburgess** [comment]
@saneef Ok yeah I made a small blunder in the logging function. I'll patch that now, and you'll get redirects displaying the url as expecfted.

Again, appreciate your help and feedback!

**Comment by bradleyburgess** [comment]
Ok, `v1.3.1` is published, which fixes this bug.
